### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by dmaglio** [nsf/obkey#3]
Traceback (most recent call last):
  File "/usr/bin/obkey", line 49, in <module>
    ktbl = obkey_classes.KeyTable(al, ob)
  File "/usr/lib/python2.7/site-packages/obkey_classes.py", line 188, in __init__
    self.apply_cqk_initial_value()
  File "/usr/lib/python2.7/site-packages/obkey_classes.py", line 366, in apply_cqk_initial_value
    cqk_accel_key, cqk_accel_mods = key_openbox2gtk(self.ob.keyboard.chainQuitKey)
  File "/usr/lib/python2.7/site-packages/obkey_classes.py", line 90, in key_openbox2gtk
    toks = obstr.split("-")
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by nsf** [comment]
Yeah, sorry, I'm not maintaining the probject anymore. If you want to fix the bug, fix it yourself. I'm okay with pull requests.
